### ISSUE TITLE
require 'net/ntlm/version' in spec/lib/net/ntlm/version_spec.rb

### ISSUE THREAD

**Issue by movitto** [WinRb/rubyntlm#12]
Greetings, when I try to run this spec in the subject either via 'rake spec' or via rspec manually, I get the following error:

```
rubyntlm-0.4.0]$ rake spec
<snip>
No DRb server is running. Running in local process instead ...
/home/mmorsi/workspace/fedora/rubygem-rubyntlm/rubyntlm-0.4.0/spec/lib/net/ntlm/version_spec.rb:3:in `<top (required)>': uninitialized constant Net::NTLM::VERSION (NameError)
	from /home/mmorsi/.gem/ruby/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
<snip>
```

I noticed no include for 'net/ntlm/version' in lib/net/ntlm.rb. When I add this require to the file, everything works as intended.

Thank you for your time.

**Comment by sneal** [comment]
Fixed by #17, although you should be using Bundler to execute the specs.

Oddly it works without the additional require when running through bundler `bundle install && bundle exec rake`. Bundler must somehow end up changing the execution context and requiring the version file.
