### ISSUE TITLE
Gem should not define VERSION for ntlm-http Gem

### ISSUE THREAD

**Issue by ddoherty03** [WinRb/rubyntlm#13]
Your code is defining Net::NTLM::VERSION, but there is another gem with the same version string but different version numbers and this is causing a conflict. See https://github.com/savonrb/httpi/issues/127

Why not just define your own version string?  Say, RUBYNTLM::VERSION?

**Comment by pcai** [comment]
> It's not as simple as just defining RUBYNTLM::VERSION. Both gems are derived from the same codebase so they actually use the net/ntlm namespace. While doing so would definitely fix your VERSION issue it would not stop the gems from overriding each other.

If this is true there is nothing that can be done here. The correct solution is to stop using `ntlm-http` gem (last released [15 years ago](https://rubygems.org/gems/ntlm-http))

closing wontfix
