### ISSUE TITLE
Not work with russian logins

### ISSUE THREAD

**Issue by crmaxx** [WinRb/rubyntlm#29]
Ruby < 2.4 has issue with String.upcase where string in unicode.

``` ruby
2.3.1 :001 > "Администратор".upcase
 => "Администратор"
2.3.1 :002 > require "unicode_utils/upcase"
 => true
2.3.1 :003 > UnicodeUtils.upcase("Администратор")
 => "АДМИНИСТРАТОР"
```

**Comment by pcai** [comment]
Thanks. `UnicodeUtils.upcase` doesnt exist anymore, closing. #37 and #43 appear to track the work required for non-ascii logins
