### ISSUE TITLE
Bind fails when username contains character 'ß' (LATIN SMALL LETTER SHARP S) and ntlmv2_hash

### ISSUE THREAD

**Issue by gupta-kanika-dev** [WinRb/rubyntlm#43]
### Issue:
NTLM binding fails with Net::NTLM.ntlmv2_hash when username passed a parameter contains character 'ß' (LATIN SMALL LETTER SHARP S).
To fix this using a workaround, we patched the method Net::NTLM.ntlmv2_hash  to use ActiveSupport::Multibyte::Chars#upcase for upcasing the user and domain. 

       def ntlmv2_hash(user, password, target, opt={})
        if is_ntlm_hash? password
          decoded_password = EncodeUtil.decode_utf16le(password)
          ntlmhash = [decoded_password.upcase[33,65]].pack('H32')
        else
          ntlmhash = ntlm_hash(password, opt)
        end
>         userdomain = user.upcase + target
        unless opt[:unicode]
          userdomain = EncodeUtil.encode_utf16le(userdomain)
        end
        OpenSSL::HMAC.digest(OpenSSL::Digest::MD5.new, ntlmhash, userdomain)
       end

>  **Net::NTLM.ntlmv2_hash patched like below:**

        def ntlmv2_hash(user, password, target, opt={})
        if is_ntlm_hash? password
          decoded_password = EncodeUtil.decode_utf16le(password)
          ntlmhash         = [decoded_password.upcase[33, 65]].pack('H32')
        else
          ntlmhash = ntlm_hash(password, opt)
        end
        userdomain = user + target
        userdomain = EncodeUtil.decode_utf16le(userdomain) if opt[:unicode]
>       userdomain = userdomain.mb_chars.upcase.to_s
        userdomain = EncodeUtil.encode_utf16le(userdomain)
        OpenSSL::HMAC.digest(OpenSSL::Digest::MD5.new, ntlmhash, userdomain)
        end

### Platform and gem used:
Rails: 6.0.3.6
Ruby: 2.7.2
rubyntlm: 0.6.3
net-ldap: 0.16.3 (also tested with latest version 0.17.0)

### More about scenario and workaround tried:
Till Rails 5.2, ActiveSupport::Multibyte::Chars#upcase was being maintained by Rails community and it provides casemapping for character 'ß' like this:

- "Üßàùªñ1".mb_chars.upcase.to_s => "ÜßÀÙªÑ1"
notice upper case-mapping for char 'ß' is 'ß' only.

Since Rails 6.0, ActiveSupport::Multibyte::Chars#upcase is deprecated and started calling String#upcase (https://rubydoc.info/stdlib/core/String#upcase-instance_method) internally instead of maintaining its own implementation. It provides case-mapping for character 'ß' like this in Rails 6.0:

- "Üßàùªñ1".mb_chars.upcase.to_s => "ÜSSÀÙªÑ1"
notice upper case-mapping for char 'ß' is 'SS' only.

**Note:** However if we notice, rubyntlm gem has always been using String#upcase (https://rubydoc.info/stdlib/core/String#upcase-instance_method) for case-mapping, which do not work well when username contains character 'ß'. 
Now, the extra support which we were taking from ActiveSupport::Multibyte::Chars#upcase is dropped in Rails 6.0. the issue falls back to the output of ntlmv2_hash and because of this the final binding with NTLM fails.

Any thoughts or feedback will be helpful to overcome this issue.

**Comment by pcai** [comment]
Hi - thanks. I'm unclear if this is specific to your systems or not, but my understanding is that in MOST languages and locales, `ß` _should_ upcase to `SS`. Since you mentioned `ActiveSupport::Multibyte::Chars#upcase` was working for you, you might need to vendor the version from rails 5.2 and continue to use that. 

If instead you can provide confirmation that `ß` should not be touched by `upcase` as part of some spec in the ntlm protocol (and not a quirk of a system-specific configuration) then it would make sense to treat this as a bug. Please reopen if that is the case.
