### ISSUE TITLE
Ciphers unsupported by default provider in OpenSSL 3

### ISSUE THREAD

**Issue by paulvt** [WinRb/rubyntlm#49]
In OpenSSL 3, some considered weak ciphers and digests were moved to the legacy provider. Because it is not loaded by default, rubyntlm does not work.

```
  1) Net::NTLM::Client::Session#sign_message signs a message and when KEY_EXCHANGE is true
     Failure/Error: rc4 = OpenSSL::Cipher.new("rc4")
     
     OpenSSL::Cipher::CipherError:
       unsupported
     # ./lib/net/ntlm/client/session.rb:128:in `initialize'

....
  6) Net::NTLM::Message::Type2 should generate a type 3 response
     Failure/Error: OpenSSL::Digest::MD4.digest pwd
     
     OpenSSL::Digest::DigestError:
       Digest initialization failed: initialization error
     # ./lib/net/ntlm.rb:149:in `ntlm_hash'
```

The user needs either to enable the provider via the configuration (very inconvenient), or access the ciphers in the legacy provider programmatically, see: https://github.com/ruby/openssl/issues/500#issuecomment-1100660910.

The new Debian and new Ubuntu versions (amongst which 22.04 LTS) ship OpenSSL 3.

**Comment by shayonj** [comment]
I proposed a short term gap here - https://github.com/WinRb/rubyntlm/pull/63. At least on bundler based installations you can point to the relvant commit via `git`, but yes would be great if get in some form of patch in for openSSL3 in main branch 🙏🏾
