### ISSUE TITLE
Anonymous Authentication Does Not Work

### ISSUE THREAD

**Issue by zeroSteiner** [WinRb/rubyntlm#52]
The client can not anonymously authenticate to a remote end point using either NTLMv1 or NTLMv2. In both cases, when the username and password are blank, the session key should be set to a specific value per [MS-NLMP section 3.4](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/d1c86e81-eb66-47fd-8a6f-970050121347).

Fixed by #45.

**Comment by pcai** [comment]
resolved in https://github.com/WinRb/rubyntlm/pull/45
