### ISSUE TITLE
New release for OpenSSL 3.x compatibility

### ISSUE THREAD

**Issue by petergoldstein** [WinRb/rubyntlm#57]
Seeing failures in gems that have this as a dependency because of the OpenSSL 3.x compatibility issue that has already been fixed in main.  Can we get a new release so that these other gems can pull in this fix?

**Comment by pcai** [comment]
hi @mwrock anything I can do to help here? I maintain a few gems including httpi that have a dependency on this. Happy to help with some chores like pushing new rubygems releases - if you are open to it

**Comment by shayonj** [comment]
There is also another related issue w/ openSSL3. Proposed a PR here - https://github.com/WinRb/rubyntlm/pull/63

Would love for a new release with both the fixes if possible 🙏🏾

**Comment by pcai** [comment]
Hi. I am helping out with this gem now. I've been trying to clear out a few cobwebs and will attempt to cut a release today.

**Comment by pcai** [comment]
Released [v0.6.4](https://github.com/WinRb/rubyntlm/releases/tag/v0.6.4) with a few fixes including openssl3 related ones. I've confirmed this addresses issues we were seeing in the httpi test suite, e.g. https://github.com/savonrb/httpi/issues/243

closing as resolved, thanks for your patience everyone.
